endpoints:
  health:
    enabled: true
    sensitive: false

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        health-check-critical-timeout: 1m
        enabled: true
        fail-fast: true
  data:
    mongodb:
      host: mongo
  zipkin:
    baseUrl: http://zipkin:9411

hystrix:
  stream:
    queue:
      send-id: false
    amqp:
      send-id: false

# public key used for verifying JWT signature
security:
  jwt:
    public:
      key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwR84LFHwnK5GXErnwkmD
        mPOJl4CSTtYXCqmCtlbF+5qVOosu0YsM2DsrC9O2gun6wVFKkWYiMoBSjsNMSI3Z
        w5JYgh+ldHvA+MIex2QXfOZx920M1fPUiuUPgmnTFS+Z3lmK3/T6jJnmciUPY1pe
        h4MXL6YzeI0q4W9xNBBeKT6FDGpduc0FC3OlXHfLbVOThKmAUpAWFDwf9/uUA//l
        3PLchmV6VwTcUaaHp5W8Af/GU4lPGZbTAqOxzB9ukisPFuO1DikacPhrOQgdxtqk
        LciRTa884uQnkFwSguOEUYf3ni8GNRJauIuW0rVXhMOs78pKvCKmo53M0tqeC6ul
        +QIDAQAB
        -----END PUBLIC KEY-----


