---
spring:
  profiles: default
  data:
    mongodb:
      database: testingDb
server:
  port: 8080


---
spring:
  profiles: docker
  data:
    mongodb:
      database: testingDb
      host: mongo
server:
  port: 8080