#endpoints.health.enabled=true
#endpoints.health.sensitive=false
#
#
#spring.cloud.consul.discovery.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}
#spring.cloud.consul.discovery.preferIpAddress=true
##spring.cloud.consul.host=consul
#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500