---
spring:
  profiles: default
  data:
    mongodb:
      database: testingDb

zipkin:
    baseUrl: http://localhost:9411

server:
  port: 8080


---
spring:
  profiles: docker
  data:
    mongodb:
      database: testingDb
      host: mongo
  zipkin:
      baseUrl: http://zipkin:9411
server:
  port: 8080
