endpoints:
  health:
    enabled: true
    sensitive: false

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        health-check-critical-timeout: 1m
        enabled: true
        fail-fast: true
  data:
    mongodb:
      host: mongo
  zipkin:
    baseUrl: http://zipkin:9411

hystrix:
  stream:
    queue:
      send-id: false
    amqp:
      send-id: false

# public key used for verifying JWT signature
security:
  jwt:
    public:
      key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5OkvKiGATSjBBMTsNzwa
        X85ZpmV/kREwRT6k5FYtE23RhRwDtSwaeIUmNBfmwbflQv//OMRokZqt/b0+d0M6
        gDJ8qHFrfruPpLURznAE/SS+e6bBbxuVEN7exEkf+W2vLehm5P9W0Plf1CopMy/O
        h40/yAPmvTLSOcPxvOaFsFPha43nZHzaNXNRXjYRELRXufpkoC+gisnXeQpR21AY
        SFWL83CrjlM/1QaPMN5QwugjeFl28HBxgTjLP6XxI6kBYD/CjToW+UlpAuI/IE7Z
        hRV6QZqAhJ3czJiB4qSFp42/+7/APHLkks5Z3Jl9F9R36m+lb0v+45QicqDXBHzA
        gwIDAQAB
        -----END PUBLIC KEY-----


