zuul:
  routes:
    items:
      path: /api/items/**
      serviceId: itemManagementService
      stripPrefix: true
    shops:
      path: /api/shops/**
      serviceId: shopService
      stripPrefix: true
      
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon:
  connect-timeout: 5000
  read-timeout: 10000