### empty for now
spring:
  jackson:
      serialization:
        write-dates-as-timestamps: false
---
spring:
  profiles: default
  data:
      mongodb:
        database: itemDb
server:
  port: 8080

---
spring:
  profiles: docker
  data:
    mongodb:
      database: itemDb
      host: mongo
server:
  port: 8080

