### empty for now
---
spring:
  profiles: default
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080

---
spring:
  profiles: docker
  cloud:
    consul:
      host: consul
server:
  port: 8080