### empty for now
spring:
  jackson:
      serialization:
        write-dates-as-timestamps: false

  zipkin:
    baseUrl: http://localhost:9411
#    locator:
#      discovery:
#        enabled:
---
spring:
  profiles: default
  data:
      mongodb:
        database: itemDb
server:
  port: 8080

---
spring:
  profiles: docker
  data:
    mongodb:
      database: itemDb
      host: mongo
  zipkin:
      baseUrl: http://zipkin:9411
server:
  port: 8080

