spring:
  profiles: default
server:
  port: 8080

zuul:
  routes:
    items:
      path: /api/items/**
      serviceId: itemManagementService
      stripPrefix: true
    shops:
      path: /api/shops/**
      serviceId: shopService
      stripPrefix: true
    calculation:
      path: /api/calculation/**
      serviceId: calculationService
      stripPrefix: true
    shipping:
      path: /api/shipping/**
      serviceId: shippingService
      stripPrefix: true
    auth:
      path: /api/auth/**
      serviceId: authService
      stripPrefix: true
  sensitiveHeaders: Cookie,Set-Cookie
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon:
  connect-timeout: 5000
  read-timeout: 10000

zipkin:
  baseUrl: http://localhost:9411

endpoints:
  health:
    enabled: true
    sensitive: false

testing:
  property: "from local appplication.yml"