spring:
  application:
    name: itemManagement
  cloud:
    consul:
      config:
        enabled: true
        prefix: configuration
        fail-fast: false
        format: yaml
#        default-context: all ## folder nae that all apps read
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        health-check-critical-timeout: 1m
      host: localhost
      port: 8500


endpoints:
  health:
    enabled: true
    sensitive: false

