## this file contains properties that are used when configuration is not read from consul
spring:
  profiles: default
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        health-check-critical-timeout: 1m
        fail-fast: true
  jackson:
        serialization:
          write-dates-as-timestamps: false
  zipkin:
    baseUrl: http://localhost:9411

