## this file contains properties that are used when configuration is not read from consul
spring:
  profiles: default
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        health-check-critical-timeout: 1m
        fail-fast: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  zipkin:
    baseUrl: http://localhost:9411
  data:
    mongodb:
      database: shippingDb

security:
  jwt:
    public:
      key: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5OkvKiGATSjBBMTsNzwa
        X85ZpmV/kREwRT6k5FYtE23RhRwDtSwaeIUmNBfmwbflQv//OMRokZqt/b0+d0M6
        gDJ8qHFrfruPpLURznAE/SS+e6bBbxuVEN7exEkf+W2vLehm5P9W0Plf1CopMy/O
        h40/yAPmvTLSOcPxvOaFsFPha43nZHzaNXNRXjYRELRXufpkoC+gisnXeQpR21AY
        SFWL83CrjlM/1QaPMN5QwugjeFl28HBxgTjLP6XxI6kBYD/CjToW+UlpAuI/IE7Z
        hRV6QZqAhJ3czJiB4qSFp42/+7/APHLkks5Z3Jl9F9R36m+lb0v+45QicqDXBHzA
        gwIDAQAB
        -----END PUBLIC KEY-----

server:
  port: 8090